import type { Project } from "./types"

export const projects: Project[] = [
  {
    artNo: "01",
    slug: "gosmartlib",
    kind: "web",
    name: "GO!SmartLib",
    category: { nl: "Full-stack webapp · klantproject", en: "Full-stack web app · client project" },
    status: "shipped",
    years: "2025 – 2026",
    team: { nl: "AP-teamproject voor GO! scholen", en: "AP team project for GO! schools" },
    summary: {
      nl: "Bibliotheekplatform voor scholen met Smartschool-login, uitleenbeheer, reviews en aanbevelingen over meerdere campussen.",
      en: "Library platform for schools with Smartschool login, lending management, reviews and recommendations across multiple campuses.",
    },
    details: {
      nl: "GO!SmartLib combineert een gedeelde boekencatalogus, de volledige uitleenflow, sociale leesfeatures en aanbevelingen achter één responsieve webinterface. Inloggen verloopt via Smartschool OAuth 2.0 met stateless JWT's en vier rollen (leerling, leerkracht, admin, super admin), met strikte data-isolatie per school. De GitLab-repo is afgeschermd.",
      en: "GO!SmartLib combines a shared book catalogue, the full lending flow, social reading features and recommendations behind one responsive web interface. Sign-in runs on Smartschool OAuth 2.0 with stateless JWTs and four roles (student, teacher, admin, super admin), with strict data isolation per school. The GitLab repo is private.",
    },
    role: {
      nl: "Rolgebaseerde routing en dashboardtegels, leeslijsten, gamification en aankondigingen.",
      en: "Role-based routing and dashboard tiles, reading lists, gamification and announcements.",
    },
    tech: ["TypeScript", "Next.js", "React", "Java", "Spring Boot", "MySQL", "Traefik", "Docker"],
    images: ["/GSLSS.png", "/GSLSS2.png", "/GSLSS3.png"],
  },
  {
    artNo: "02",
    slug: "antwerp-bmx-raceday",
    kind: "web",
    name: "Antwerp BMX Raceday",
    category: { nl: "Wedstrijdapp · klantproject", en: "Race-day app · client project" },
    status: "in-development",
    years: "2026 – 2027",
    team: { nl: "AP-teamproject, team van 4", en: "AP team project, team of 4" },
    summary: {
      nl: "App om clubwedstrijden van Antwerp BMX te draaien: inschrijven, MOTO's samenstellen, starthek, finishregistratie en klassementen.",
      en: "App to run Antwerp BMX club races: registration, building MOTOs, start gate, finish registration and standings.",
    },
    details: {
      nl: "Antwerp BMX (±140 leden, riders van 5 tot 65 jaar) organiseert binnenclubwedstrijden met 80 tot 500 riders en elke minuut een start. Vandaag loopt dat via Google Forms, een eigen tool en papier. De app vervangt die keten: accounts voor ouders en riders, verzekeringscontrole, rollen per wedstrijd (jury, parc fermé, starthek, finish, speaker), realtime resultaten op de gsm en traceerbare correcties. Loopt in vijf sprints tot de eindpresentatie in januari 2027.",
      en: "Antwerp BMX (about 140 members, riders aged 5 to 65) runs club races with 80 to 500 riders and a start every minute. Today that runs on Google Forms, a home-made tool and paper. The app replaces that chain: accounts for parents and riders, insurance checks, per-race roles (jury, parc fermé, start gate, finish, speaker), real-time results on mobile and traceable corrections. Runs in five sprints until the final presentation in January 2027.",
    },
    tech: [],
    // No stack chosen yet: the drawing shows the race-day flow it digitises instead.
    drawing: {
      nl: ["Inschrijven", "MOTO's", "Starthek", "Finish", "Klassement"],
      en: ["Registration", "MOTOs", "Start gate", "Finish", "Standings"],
    },
  },
  {
    artNo: "03",
    slug: "ripple",
    kind: "web",
    name: "Ripple",
    category: { nl: "Hackathon · SD Worx-case", en: "Hackathon · SD Worx case" },
    status: "shipped",
    years: "2026",
    team: { nl: "Team van 4, Tectonic Hackathon 2026", en: "Team of 4, Tectonic Hackathon 2026" },
    summary: {
      nl: "Trust layer voor versnipperde bedrijfskennis: vergelijkt documenten, geeft elke bron een score en wijst bij tegenspraak de juiste expert aan.",
      en: "Trust layer for scattered company knowledge: compares documents, scores every source and points to the right expert when sources disagree.",
    },
    details: {
      nl: "Gebouwd op de Tectonic Hackathon 2026 voor de case van SD Worx: hoe maak je versnipperde kennis vindbaar, betrouwbaar en deelbaar? Een consultant kiest bronnen, Ripple scoort ze op recentheid, autoriteit en tegenstrijdigheden. Is de beste score te laag, dan vraag je een expert om één feit te bevestigen en worden alle scores herrekend. Alleen projectleden zien een project.",
      en: "Built at Tectonic Hackathon 2026 for the SD Worx case: how do you make scattered knowledge findable, trustworthy and shareable? A consultant picks sources and Ripple scores them on recency, authority and conflicts. When the best score is too low, you ask an expert to verify one fact and every score recalculates. Only project members can see a project.",
    },
    tech: ["TypeScript", "Next.js", "Tailwind CSS", "shadcn/ui", "Gemini"],
    repoUrl: "https://github.com/dylanhavelaerts/Tectonic-Hackaton",
  },
  {
    artNo: "04",
    slug: "travel-planning-architecture",
    kind: "web",
    name: "Travel Planning Platform",
    category: { nl: "Software-architectuur", en: "Software architecture" },
    status: "shipped",
    years: "2026",
    team: { nl: "AP-team van 5", en: "AP team of 5" },
    summary: {
      nl: "Architectuur-case voor een platform om samen reizen te plannen: modulaire monoliet, C4-modellen, ADR's en vijf proof-of-concepts.",
      en: "Architecture case for a platform to plan trips together: modular monolith, C4 models, ADRs and five proofs of concept.",
    },
    details: {
      nl: "Een platform waarmee vrienden samen reizen plannen met gedeelde budgetten, activiteiten en koppelingen met externe reisproviders. Gekozen stijl: een modulaire monoliet in Node.js, met ACID-transacties voor gedeelde budgetten en duidelijke modulegrenzen richting microservices. Uitgewerkt met zeven kwaliteitsattributen, een C4-model in Structurizr, zes ADR's (MADR) en vijf deploybare proof-of-concepts op Docker Swarm.",
      en: "A platform where friends plan trips together with shared budgets, activities and integrations with external travel providers. Chosen style: a modular monolith in Node.js, with ACID transactions for shared budgets and clear module boundaries that keep a path to microservices. Worked out with seven quality attributes, a C4 model in Structurizr, six ADRs (MADR) and five deployable proofs of concept on Docker Swarm.",
    },
    role: {
      nl: "ADR-003 (authenticatie) en POC 1: OAuth2 met eigen JWT.",
      en: "ADR-003 (authentication) and POC 1: OAuth2 with our own JWT.",
    },
    tech: ["JavaScript", "Node.js", "Express", "React", "Docker", "Traefik"],
    images: ["/c4-context.png", "/c4-containers.png", "/c4-deployment.png"],
    repoUrl: "https://github.com/Tiebe-Vaes/travel-planning-architecture",
  },
  {
    artNo: "05",
    slug: "locallend",
    kind: "mobile",
    name: "LocalLend",
    category: { nl: "Mobiele app", en: "Mobile app" },
    status: "shipped",
    summary: {
      nl: "Verhuurapp waarmee buren toestellen en gereedschap uitlenen, met zoeken op kaart, boekingen en reviews.",
      en: "Rental app for neighbours to lend out appliances and tools, with map search, bookings and reviews.",
    },
    details: {
      nl: "Eigenaars plaatsen items met foto, prijs, categorie en een beschikbaarheidskalender. Huurders zoeken items in de buurt via een lijst of een interactieve Google Map, boeken de dagen die ze nodig hebben en laten achteraf een review achter. Realtime sync via Firestore, zodat boekingen meteen bij iedereen verschijnen.",
      en: "Owners list items with a photo, price, category and availability calendar. Renters find nearby items in a list or on an interactive Google Map, book the days they need and leave a review afterwards. Real-time sync through Firestore, so bookings show up for everyone instantly.",
    },
    tech: ["Dart", "Flutter", "Riverpod", "Firebase", "Google Maps"],
    images: ["/LLSS1.png", "/LLSS2.png", "/LLSS3.png", "/LLSS4.png"],
    repoUrl: "https://github.com/Tiebe-Vaes/LocalLend",
  },
  {
    artNo: "06",
    slug: "kart-race-app",
    kind: "mobile",
    name: "Kart Race App",
    category: { nl: "Mobiele app", en: "Mobile app" },
    status: "shipped",
    years: "2026",
    summary: {
      nl: "App voor kartracers (RedLine): circuits bekijken, races aanmaken, een plek reserveren en live chatten met de deelnemers.",
      en: "App for kart racers (RedLine): browse tracks, create races, reserve a spot and chat live with the participants.",
    },
    details: {
      nl: "Je bekijkt beschikbare circuits, maakt zelf races aan op een track en reserveert een plek. Elke race heeft een eigen live chatroom zodat deelnemers kunnen afspreken, en je kan tracks en races beoordelen. Authenticatie en data via Firebase Auth en Firestore.",
      en: "You browse available tracks, create your own races on a circuit and reserve a spot. Every race has its own live chatroom so participants can coordinate, and you can rate tracks and races. Authentication and data via Firebase Auth and Firestore.",
    },
    tech: ["TypeScript", "React Native", "Expo", "Firebase"],
    images: ["/Redline1.jpeg", "/Redline2.jpeg", "/Redline3.jpeg", "/Redline4.jpeg"],
    repoUrl: "https://github.com/Tiebe-Vaes/kart-race-app",
  },
  {
    artNo: "07",
    slug: "petalpurrs",
    kind: "other",
    name: "PetalPurrs",
    category: { nl: "Browsergame", en: "Browser game" },
    status: "shipped",
    summary: {
      nl: "Cozy theewinkelgame: zet thee voor kat-klanten, verdien fooien en ontgrendel nieuwe koppen en theesoorten.",
      en: "Cozy tea-shop game: brew tea for cat customers, earn tips and unlock new cups and tea types.",
    },
    details: {
      nl: "Lees de wens in de tekstballon van elke kat en zet de juiste thee met de juiste kop, temperatuur en extra's. Een perfecte match levert een fooi op. Werk de wachtrij af, level op, ontgrendel zeldzamere theesoorten en beheer je tuin om je voorraad aan te vullen. Gebouwd met React via CDN, zonder buildstap.",
      en: "Read each cat's wish in its speech bubble and brew the right tea with the right cup, temperature and extras. A perfect match earns a tip. Work through the queue, level up, unlock rarer teas and tend your garden to restock. Built with React via CDN, with no build step.",
    },
    tech: ["JavaScript", "React", "CSS"],
    images: ["/PPSS1.png"],
    repoUrl: "https://github.com/Tiebe-Vaes/PetalPurrs",
    liveUrl: "https://petalpurrs.wordpress.com/",
  },
  {
    artNo: "08",
    slug: "mono",
    kind: "other",
    name: "Mono",
    category: { nl: "2D-platformer", en: "2D platformer" },
    status: "shipped",
    years: "2025 – 2026",
    summary: {
      nl: "2D-platformer: levels doorlopen, spikes en tornado's ontwijken en gems verzamelen.",
      en: "2D platformer: clear levels, dodge spikes and tornadoes and collect gems.",
    },
    details: {
      nl: "Gebouwd met C# en MonoGame op .NET 9. Eigen animaties, een state-systeem voor de gamestates en factories voor de obstakels, met een moeilijkheidsgraad die per level oploopt.",
      en: "Built with C# and MonoGame on .NET 9. Custom animations, a state system for the game states and factories for the obstacles, with difficulty that ramps up per level.",
    },
    tech: ["C#", ".NET", "MonoGame"],
    images: ["/MONOSS1.png"],
    repoUrl: "https://github.com/Tiebe-Vaes/Mono",
  },
  {
    artNo: "09",
    slug: "study-countdown",
    kind: "other",
    name: "Study Countdown",
    category: { nl: "Desktopapp", en: "Desktop app" },
    status: "shipped",
    summary: {
      nl: "Desktopapp die aftelt naar deadlines en examens.",
      en: "Desktop app that counts down to deadlines and exams.",
    },
    details: {
      nl: "Een eigen desktopapp die deadlines en examens bijhoudt en zichtbaar aftelt, gebouwd met Angular 20 en Electron.",
      en: "A personal desktop app that tracks deadlines and exams and counts down to them, built with Angular 20 and Electron.",
    },
    tech: ["TypeScript", "Angular", "Electron"],
  },
]
